// IMPORTAMOS EL COMPONENT BASE DE ANTD Y SU INTERFAZ (TYPE)
import BaseButton, { ButtonProps } from 'antd/es/button';

// DEFINIMOS NUESTRO COMPONENTE PROPIO SIGUIENDO UN PATRON ADAPTADOR
// USAMOS EL TYPE DE ANTD PARA NO TENER QUE REESCRIBIR LOS PROPS QUE VA A RECIBIR NUESTRO BOTON
// ASI TENEMOS TODA LA FUNCIONALIDAD DEL COMPONENT DE ANTD EN NUESTRO BOTON
const Button = ({ children, ...props }: ButtonProps) => {
  return (
    <BaseButton {...props} style={{ backgroundColor: 'red' }}>
      {children}
    </BaseButton>
  );
};

export default Button;

// POR QUE HACEMOS ESTO? PORQUE ESTE COMPONENTE LO UTILIZAMOS A TRAVES DE TODA LA APLICACION, SI MAÑANA SE DECIDIERA
// CAMBIAR LA LIBRERIA DE COMPONENTES, SOLO TENDRIAMOS QUE CAMBIARLO AQUI, Y LA APLICACION SEGUIRIA FUNCIONANDO, DE LO
// CONTRARIO TENDRIAMOS QUE IR A CADA SITIO DONDE SE UTILICE EL COMPONENT DE ANTD Y CAMBIAR, ADEMAS ESTO PERMITE UNA PERSONALIZACION
// TANTO DE ESTILOS COMO DE FUNCIONALIDAD ADECUANDOLO A LAS NECESIDADES DEL PROYECTO

// ESTE COMPONENT Y DISEÑO TAMBIEN PERMITE QUE SE LE PUEDA AGREGAR DE FORMA GENERAL UNA FUNCIONALIDAD POR DEFECTO Y ESPECIFICA
// SIN TENER QUE REPETIRLA EN CADA SITIO DONDE SE USE
